version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_CRM_API_URL=http://localhost:8001
      - NEXT_PUBLIC_USER_API_URL=http://localhost:8002
      - NEXT_PUBLIC_WORKFLOW_API_URL=http://localhost:8003
      - NEXT_PUBLIC_AI_API_URL=http://localhost:8004
